### ISSUE TITLE
I would love to know where I'm going wrong

### ISSUE THREAD

**Issue by ludo1960** [contentacms/contenta_jsonapi#359] opened 2019-04-23 15:44 UTC
Hi guys,
I've re-installed contenta a number of times and I still cant see any content.
I go to http://contenta.local.com/recipes/thai-green-curry and I get:
```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Symfony\Component\Routing\Exception\RouteNotFoundException</em>: Route &quot;jsonapi.node--recipe.individual&quot; does not exist. in <em class="placeholder">Drupal\Core\Routing\RouteProvider-&gt;getRouteByName()</em> (line <em class="placeholder">201</em> of <em class="placeholder">core/lib/Drupal/Core/Routing/RouteProvider.php</em>). <pre class="backtrace">Drupal\Core\Routing\UrlGenerator-&gt;getRoute(&#039;jsonapi.node--recipe.individual&#039;) (Line: 271)
Drupal\Core\Routing\UrlGenerator-&gt;generateFromRoute(&#039;jsonapi.node--recipe.individual&#039;, Array, Array, 1) (Line: 105)
Drupal\Core\Render\MetadataBubblingUrlGenerator-&gt;generateFromRoute(&#039;jsonapi.node--recipe.individual&#039;, Array, Array, 1) (Line: 753)
Drupal\Core\Url-&gt;toString(1) (Line: 48)
Drupal\jsonapi_extras\EntityToJsonApi-&gt;serialize(Object, Array) (Line: 70)
Drupal\jsonapi_extras\EntityToJsonApi-&gt;normalize(Object) (Line: 371)
contenta_enhancements_node_view_alter(Array, Object, Object) (Line: 539)
Drupal\Core\Extension\ModuleHandler-&gt;alter(&#039;node_view&#039;, Array, Object, Object) (Line: 286)
Drupal\Core\Entity\EntityViewBuilder-&gt;buildMultiple(Array) (Line: 220)
Drupal\Core\Entity\EntityViewBuilder-&gt;build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer-&gt;doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer-&gt;render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber-&gt;onViewRenderArray(Object, &#039;kernel.view&#039;, Object)
call_user_func(Array, Object, &#039;kernel.view&#039;, Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.view&#039;, Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 67)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 45)
Drupal\jsonapi\StackMiddleware\FormatSetter-&gt;handle(Object, 1, 1) (Line: 49)
Asm89\Stack\Cors-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>
```
Can someone please suggest where I'm going wrong?

**Comment by e0ipso** [comment] 2019-04-23 20:48
There's nothing you did wrong. There is an issue in one of the modules: https://www.drupal.org/project/jsonapi_extras/issues/3049221

You can try out the patch there or wait for a release on the module.

**Comment by ludo1960** [comment] 2019-04-23 21:00
Thanks for that, thought I was going nuts!

**Comment by e0ipso** [comment] 2019-04-25 14:13
This is a duplicate of #357

**Closed as completed by e0ipso** 2019-04-25 14:13 UTC
