### ISSUE TITLE
suggestion : bigger text-area for the content field 

### ISSUE THREAD

**Issue by yann-yinn** [contentacms/contenta_jsonapi#178] opened 2017-08-28 08:54 UTC
Hello ! Migrating my blog to contenta, i noticed "body" text area is very little in the back-office.
_(PS : i tried to change rows for body field without success, maybe a css override ?)_
Contenta is "all about the content", so it could be interesting to get closer of medium or wordpress concerning the content textarea, see screenshots. Because this is probably where content editors spend most of their times.  What do you think of it ?  

**Contenta**  
<img width="1420" alt="contenta-body" src="https://user-images.githubusercontent.com/335495/29766469-26249e72-8bdf-11e7-9b47-54db41ccf305.png">

**Drupal 8 seven theme**
<img width="1409" alt="capture d ecran 2017-08-28 a 22 54 36" src="https://user-images.githubusercontent.com/335495/29793122-01b5c138-8c43-11e7-8493-54fc55e7087e.png">

**Wordpress**
<img width="1408" alt="capture d ecran 2017-08-28 a 10 53 59" src="https://user-images.githubusercontent.com/335495/29766475-28b564e6-8bdf-11e7-9fb7-475170b2fcad.png">

**Medium** 
<img width="1198" alt="capture d ecran 2017-08-28 a 10 53 32" src="https://user-images.githubusercontent.com/335495/29766482-2a97fa1c-8bdf-11e7-82b2-7fcc491201d1.png">

**Comment by dawehner** [comment] 2017-08-28 22:58
I like to increase the size. Maybe we could fix it in materialized itself.

**Comment by e0ipso** [comment] 2017-08-30 05:15
I created an issue in the admin theme project: https://github.com/briancwald/material_admin/issues/35

**Comment by briancwald** [comment] 2017-08-30 13:07
@nyl-auster do you mean expanding the width or height? The height is dynamic and as you add content the box will expand automatically. This is the spec defined in Material Design. The problem is that there are a lot of uses for the generic textarea, and you wouldnt want them all to be that big, but I can see how you would want that in this case. Perhaps we can create a special one-off for this.  For width, It _should_ be listening to the columns set. It's 60 by default in Drupal but if you change that for the field.

**Comment by yann-yinn** [comment] 2017-08-30 13:29
@briancwald it was not listening to the columns set in my test, manually set the size would be perfectly okay ! A tiny box on the left of the screen ( first screenshot ) does not feels right when writing a post or an article.

**Comment by e0ipso** [comment] 2018-04-27 05:52
This was fixed in the contributed theme.

**Closed as completed by e0ipso** 2018-04-27 05:52 UTC
Labels: enhancement
