### ISSUE TITLE
Cant delete content from contentacms content view

### ISSUE THREAD

**Issue by KlausJuhantalo** [contentacms/contenta_jsonapi#354] opened 2019-02-20 20:06 UTC
Cant delete content from contentacms content view /admin/content 
(this view /admin/structure/views/view/content - not edited). 

![content-view-image](https://user-images.githubusercontent.com/47831696/53120857-70aa0f00-355b-11e9-8ae9-da06cb7c0345.png)

If i select one or more nodes and press delete, there don´t come delete confirm page, it only says direct that nodes deleted, but these are not deleted. If i go and edit node i can delete it there. In content view if i select node and change it to unpublished - that works. These nodes are created with json.  Drupal core | 8.6.7

![select-deleted-image](https://user-images.githubusercontent.com/47831696/53120612-e6fa4180-355a-11e9-8b34-e913b6d8d158.png)

![deletecontentapplied-image](https://user-images.githubusercontent.com/47831696/53120624-ed88b900-355a-11e9-8bba-eeb11ec84d74.png)

![not-deleted-image](https://user-images.githubusercontent.com/47831696/53120630-f1b4d680-355a-11e9-97fd-2e62c1238501.png)

**Comment by energee** [comment] 2019-02-22 18:10
Seeing the same issue, I haven't tried to look into a solution as of yet.

**Comment by e0ipso** [comment] 2019-03-26 20:34
I have seen this problem in non-contenta Drupal installs. Maybe there is a patch/issue in the drupal.org issue queue.

**Comment by frega** [comment] 2019-03-27 09:36
@KlausJuhantalo please see https://www.drupal.org/project/drupal/issues/2670730 and CR https://www.drupal.org/node/2934349 for the cause & solution for this issue (or follow the instructions in the referenced PR above https://github.com/contentacms/contenta_jsonapi/pull/355)

**Comment by e0ipso** [comment] 2019-04-30 07:41
Fixed in https://github.com/contentacms/contenta_jsonapi/pull/355.

**Closed as completed by e0ipso** 2019-04-30 07:41 UTC
